name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
      # - name: Write env file
      #   run: |
      #     echo "MONGO_URL=${MONGO_URL}" >> .env
      #     echo "CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}" >> .env
      #     echo "CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}" >> .env
      #     echo "SENDGRID_API_KEY=${SENDGRID_API_KEY}" >> .env
      - name: Write env file
        run: |
          echo ${{ secrets }} >> .tenv

      - name: Restart Server
        run: pm2 restart web3-lagos || pm2 start --name web3-lagos npm -- start
      - name: Copy Server File
        run: cp -r .next /var/www/web3-lagos

  # deploy:
  #   needs: build
  #   runs-on: self-hosted

  #   env:
  #     NODE_ENV: production
  #     PORT: 3004
  #     MONGODB_URI: ${{ secrets.MONGODB_URI }}
